# <https://travis-ci.com/account/repositories>
language: java
jdk:
  - openjdk15

branches:
  only:
    - master

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# clean 후 Build (Build시 자동으로 test 수행)
script: "./gradlew clean build"

# 권한 추가
before_install:
  - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)
