version: "3"
services:
  test_database:
    # 컨테이너 이름을 주고 싶다면 작성한다
    # container_name: test_database
    image: mysql:5.7
    #        restart: always # 항상 켜 놓을 건 아니니까? 직접 컴포즈 up해서 테스트 하는 게 나을 듯
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - 3307:3306
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--innodb-use-native-aio=0"
#   뭐 지금은 굳이 볼륨 설정해서 쓸 건 없겠지
#    volumes:
#      - "$HOME/mnt/mysql:/var/lib/mysql"
  test_application:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - test_database
