spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_integration_db?useLegacyDatetimeCode=false&serverTimezone=GMT&useUnicode=true
    username: root
    password:
