# 공통 설정
server:
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true

spring:
  application:
    name: Strada

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

      org:
        hibernate:
          envers:
            audit_table_suffix: _history
            modified_flag_suffix: _changed
            store_data_at_delete: true

springdoc:
  version: '@springdoc.version@'

jwt:
  header: Authorization
  headerPrefix: Bearer
  keyPair[0].public: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDg1qDVoBZJkyB01xqQRy4DRMOpe4aeyNn7T8r1ozl7PHcP4HOeqBsnOEcRMFbt+7Cv9BIy1P/iOzkHkiQebN48YNl8DHM5e064x9jha3YdkjipdrqXwPJeQPNYznSPM/WNGJobp+Nw7tIPZVuLRz8QzNBRufBKLrkLzv7xZKEy5QIDAQAB
  keyPair[0].private: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAODWoNWgFkmTIHTXGpBHLgNEw6l7hp7I2ftPyvWjOXs8dw/gc56oGyc4RxEwVu37sK/0EjLU/+I7OQeSJB5s3jxg2XwMczl7TrjH2OFrdh2SOKl2upfA8l5A81jOdI8z9Y0Ymhun43Du0g9lW4tHPxDM0FG58EouuQvO/vFkoTLlAgMBAAECgYAf1u0QS3sUgLgGK8b4ewf+UQDXUaWa+0z5LI/MkMiNVd7zeeDNrTcpKuxPeBW7XlrjU/A20BiLcEEPfCfOwjKHPOADXu+3PA1A9T8/F5xJLOzA3F0d3R/yl5AIODHW9XFXMcbrtJ72vJPKkWSua+N+6Zl9kndmIe3iE7/HchfkiQJBAPgMm2k+twPvj+VR4vjzLiXTnXdLtNSiyJPN09+h3F5ewPZ1NLQdX8752T9+dr4n74mmGlc8yOPC/GK7GAGYLmkCQQDoC4/r2h5+nOKvAjPDoeWzfo+h12HNf3UkCXcpiK38TUL5x1oA/RgNwW/a+uIG/ih61sUkC4QR2uIJZrBy6EkdAkEA92y76PNh408nHfvch68qrRi0zbZ6nk/x+10opr3x70BdAnpPJArY8sBOcANZtrxnN8q0I6jCSk7JKkKt44lFYQJAfx7ubnfk4toRuWyMbS1BSG8aQsBavRiJVP+2f1N4dVLiUTIsFYSR698/5wgwUUJlbL5B6/g/FwUBdcMDAUBN5QJBAMgP22sLSbuk3qUWAEcsQs5NY8P/dByn/NJtSwM8A21MWAq7wKb9T5LuKgghTsJKeV9Fow5BDgeJ1em5uTrspw8

# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html
management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
    health:
      show-components: always
      show-details: always
  endpoints:
    web:
      exposure:
        include: "info, metrics, prometheus"

  metrics:
    tags:
      application: ${spring.application.name}
      profile: test
    export:
      prometheus.enabled: true
    distribution.percentiles.http: 0.5, 0.9, 0.95, 0.97, 0.99
    distribution.percentiles-histogram.http: true
    distribution.slo.http: 100ms, 200ms, 400ms


---
spring:
  profiles: default, local, test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db?useLegacyDatetimeCode=false&serverTimezone=GMT&useUnicode=true
    username: root
    password:

---
spring:
  profiles: feature

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-3-35-55-47.ap-northeast-2.compute.amazonaws.com:3306/test_db?useLegacyDatetimeCode=false&serverTimezone=GMT&useUnicode=true
    username: root
    password: